# Utiliser un argument pour la version de CrowdSec
ARG CROWDSEC_VERSION=v1.6.2
FROM crowdsecurity/crowdsec:${CROWDSEC_VERSION}

# Copier le script d'entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Définir l'entrypoint
ENTRYPOINT ["/entrypoint.sh"]
