# Utiliser une image Debian comme base
FROM crowdsecurity/crowdsec:v1.6.2

# Copier le script d'entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copier le fichier de secrets pour l'installation initiale
COPY secrets /etc/crowdsec/secrets

# Exposer le port du dashboard
EXPOSE 3000

# Définir l'entrypoint
ENTRYPOINT ["/entrypoint.sh"]
